return {
  {
    "utilyre/barbecue.nvim",
		event = "BufReadPost",
    name = "barbecue",
    version = "*",
    dependencies = {
      "SmiteshP/nvim-navic",
      "nvim-tree/nvim-web-devicons",
    },

    opts = {
      attach_navic = true,
      create_autocmd = true,
      include_buftypes = { "" },
      exclude_filetypes = { "toggleterm" },
      modifiers = {
        dirname = ":~:.",
        basename = "",
      },
      show_dirname = false,
      show_basename = true,
      show_modified = false,
      modified = function(bufnr) return vim.bo[bufnr].modified end,
      show_navic = true,
      lead_custom_section = function() return " " end,
      custom_section = function() return " " end,
      -- theme = "auto",
			theme = {
				normal = { bg = "#352f2d", fg = "#b4bdc3" },
			},
      context_follow_icon_color = false,
      symbols = {
        modified = "●",
        ellipsis = "…",
        separator = "",
      },
      kinds = {
        File = "",
        Module = "",
        Namespace = "",
        Package = "",
        Class = "",
        Method = "",
        Property = "",
        Field = "",
        Constructor = "",
        Enum = "",
        Interface = "",
        Function = "",
        Variable = "",
        Constant = "",
        String = "",
        Number = "",
        Boolean = "",
        Array = "",
        Object = "",
        Key = "",
        Null = "",
        EnumMember = "",
        Struct = "",
        Event = "",
        Operator = "",
        TypeParameter = "",
      },
    }
  }
}
